### PR TITLE
feat: nvim 0.9.0!

### PR DESCRIPTION
**Pull request by jmbuhr**

### CODE REVIEW

**Comment by jolars** [comment]
Thanks for the great work on this plugin and the update, but can I please suggest that you wait just a little bit longer to make support for earlier neovim versions defunct? Neovim 0.9.0 is just two days old after all and hasn't made its way to many official repositories. I'm on fedora 37, for instance, and the 0.9.0 version of neovim is still in testing. I realize that that I can lock quarto-nvim and otter to older versions (or install neovim in other ways), but I think me and most other people would prefer to not manually manage plugin versions like that. Just a suggestion!

**Comment by jmbuhr** [comment]
Thank you for the kind words and your concerns.

Initially I had planned to support different versions with explicit checks, but this turned out to introduce too much complexity that would get out of hand eventually due to breaking changes that range across neovim and different plugins. I wanted to release the version compatible with nvim 0.9 at a similar time as nvim, as I had already gotten a couple of issues from people trying it. At the current stage there is no official way of managing plugin in neovim (I think this is planned eventually), but there is no way around a plugin manager that can specify a version such as lazy.nvim or packer.nvim. Either the folks below or above nvim 0.9 will have to specify a version of their plugins and the convention would be that the latest stable release corresponds to other latest stable releases.

That said, I should and I will include a link and instructions on how to fix a version in the deprecation message.

**Comment by jmbuhr** [comment]
Reference: https://github.com/quarto-dev/quarto-nvim/commit/56b686934bcc22f8ae2a91275bf0a4d801ab3728

**Comment by has2k1** [comment]
@jmbuhr, thank you very much. I had to move 0.9.0nightly +month ago and this improves the situation remarkably.

**Pull request merged**
