### PR TITLE
Code Runner Overhaul

### LINKED ISSUE #81: Document code sending features and vim slime dependency
Hello, thank you for all the great work you're doing! Enjoying using the package so far. I wanted to use the various QuartoSend functions you have implemented, and I was able to get it to work, but it might be useful to document vim slime as a dependency / explain how to set that up. I was able to discern through error messages and some of the code in your kickstarter config, but might be clearer to include as info in the package.

### LINKED ISSUE #93: Official Molten support?
I'm wondering what you think of officially supporting [molten-nvim](https://github.com/benlubas/molten-nvim) as a code runner. Given Quarto's used as notebook style tool, running code with the Jupyter kernel seems like a great fit. 

I'm happy to do some work here if it would be welcome.

### PR DESCRIPTION
**Pull request by benlubas**
closes #93
closes #81 

### General notes
- I've pulled config out into it's own file
- The api hasn't changed, ie there are still `:QuartoSend` and `require('quarto').quartoSend()` functions (for now, thinking about removing the old lua functions), but there's now also `require('quarto.runner').run_cell(multi_lang: bool)` functions that give the user control over if the function runs multiple languages at once. I'm completely open to changing these function names if you want them to be more analogous to the current "send", "sendCell" etc.

#### Things that are working
- All of the 'old' code running functions
- a new `QuartoSendLine`
- configuring your code runner (currently the only options are Molten and Slime) with default and on a per language basis.
- excluding some languages from being run ever (default to just ignore `yaml`)

#### More changes before this PR is ready
- [x] I'm definitely going to refactor the way code runners work so they each have their own file, and export a common table of functions that we can use to cleanup the send function a little.
- [x] README needs an update to talk about these changes.
- [x] config defaults should be changed so that code running doesn't work by default (b/c the user has to install another plugin for it to work)

#### Things I'm pushing off until a later PR
- auto target switching. This ended up being too much for right now. I think that I want to discuss what exactly this should look like more in depth. The challenge here I think will be handling different runners doing different things and provide a good UX for this

### CODE REVIEW

**Comment by benlubas** [comment]
@jmbuhr Curious to hear what you think about removing the `require('quarto').quartoSend()` and similar functions.

It is a breaking change for existing users, but so is the new way that code runners are configured.

**Comment by jmbuhr** [comment]
Looks good, I'll play around with it on the weekend! :)

**Comment by jmbuhr** [comment]
This is shaping out nicely!

**Comment by jmbuhr** [comment]
- I believe we don't need the `get_config` function, we can simply use `local config = require("quarto.config").config` in those places.
- Feels great to use so far, I tried with slime and molten

Questions or requests for molten that would tie in nicely with the notebook experience (not required for the integration, just nice to haves):
- Is it possible to navigate easily into the output window, like with `K` where the first press opens the hover and the second moves the cursor there for easy copy-pasting?
- Is it possible to keep multiple output floats open at the same time to create a jupyter notebook style experience? e.g. one might want to keep the chunk output of a dataframe visible while working on a plot to remember the column names or work on multiple plots. With slime I would do so using web graphics devices (e.g. httpgd for R) that show the plots in the browser via a server, but molten could potentially deliver this out of the box.

**Comment by benlubas** [comment]
I was at some point having issues without the `get_config` function. I'll test without it.

> Is it possible to navigate easily into the output window

Yup, third keybinding [here](https://github.com/benlubas/molten-nvim#other-example-mappings)

> keep multiple output floats open at the same time

Currently no, and also going to take some time b/c the current code assumes everywhere that there is only one output open at a time and that output is on screen and below the top line. But that is something I'm working on ([here](https://github.com/benlubas/molten-nvim/issues/19) is the issue). I might implement other things before this gets finished but it'll get there eventually.

**Comment by benlubas** [comment]
I'm not sure what I was doing before, but it seems to work now

**Comment by benlubas** [comment]
@jmbuhr lmk if there's anything else that you want me to do with this.

Also letting you know that I've added virtual text output to molten, which allows for more than one output to be open at a time. It's still 'pre-release' but it's been merged to main, and works well enough to use.

**Comment by jmbuhr** [comment]
Virtual text ist a cool solution for this! Is this ready to merge from your side?

**Comment by benlubas** [comment]
Yup! I don't have anything else to add to it. I've used this for like two weeks and it seems to work pretty well.

**Comment by jmbuhr** [comment]
Perfect! I'll merge this as is then :)
Afterwards, some things might be moved around or renamed in a slight cleanup I have been meaning to do for a while.

**Pull request merged**
