### PR TITLE
feat: use quarto filetype instead of markdown

### PR DESCRIPTION
**Pull request by jmbuhr**
requires https://github.com/nvim-treesitter/nvim-treesitter/pull/4212

### CODE REVIEW

**Comment by jmbuhr** [comment]
Note to self: make sure to add the same in `otter.nvim` at the same time

**Comment by milanglacier** [comment]
Currently it seams that when commenting out the line `vim.bo.filetype = 'markdown`

otter.nvim will complain about cannot find the `quarto` parser. 

Can otter queries markdown parser when it detects quarto filetype?

**Comment by jmbuhr** [comment]
Yes, I just need to add it. Hence my note.

In facte, the whole reason I made otter.nvim as it's own plugin is to make it extendable to different filetypes and languages.

**Comment by jmbuhr** [comment]
Works with master branch of https://github.com/nvim-treesitter/nvim-treesitter but wait until their next release to avoid breaking peoples configs (e.g. lazy.nvim users likely use the latest tagged release, not the main branch)

**Comment by jmbuhr** [comment]
quarto filetype is now also used in https://github.com/jmbuhr/cmp-pandoc-references

**Comment by milanglacier** [comment]
Cool. I updated the `otter.nvim` and it works!

Let's wait until the next release of treesitter is published. 

Proposal: when the treesitter release is published, we can add a tips in the README to give the user tips to install `quarto-vim` and set `additional_vim_regex_highlighting = {'markdown'}` in treesitter configs for better syntax highlighting.

**Comment by jmbuhr** [comment]
Perfect, thanks for testing! Yes, that is a good idea. And down the line we can implement this properly with a quarto treesitter grammar. I also asked the quarto team and treesitter is already on their radar! :) https://github.com/quarto-dev/quarto/issues/66#issuecomment-1404950610

**Comment by jmbuhr** [comment]
I have also tested the additional regex highligting a bit more and will eventually add (maybe as optional) to the kickstarter configuration. btw. @milanglacier have you figured out how to disable pandoc-syntax's concealing for code block delimiters? This doesn't seem to work, but I would want to disable it by default for most users I think.

**Comment by milanglacier** [comment]
I don't find a solution that works together with treesitter's markdown
highlight and pandoc syntax together.

If you have the following configs: `TSBufDisable highlight` for
quartofiletype, and have

```lua
vim.g['pandoc#syntax#conceal#blacklist'] = { 'codeblock_delim', 'codeblock_start' }
```
then the code block delims won't be concealed.

**Comment by jmbuhr** [comment]
Good point, I had completely missed that nvim-treesitter added conceal for codeblocks. Instead of disabling all of the TS highlighting I chose to only disable the conceal. Example implementation here: https://github.com/jmbuhr/quarto-nvim-kickstarter/pull/7

**Pull request merged**
